### ISSUE TITLE
FR : Hover labels for LiMonAde

### ISSUE THREAD

**Issue by Petervos2018** [sebastien-bouffier/Bidoo#113]
I find the label drawings very cryptic, maybe it is possible to have a hover over label text telling what the button does ?

![LimonadeLabelscrop](https://user-images.githubusercontent.com/46076474/61638539-ebf22700-ac99-11e9-9d9e-f12a9b380db8.jpg)

Just like those red buttons "# 11 : 0" (which I also don't know what it does ;) )

Greetings Peter.

**Comment by sebastien-bouffier** [comment]
Yes you are right ... those are cryptic.
Thanks for your interest :)
Cheers

**Comment by therealkitman** [comment]
Hi, I agree with Peter (I was going to raise this issue too). LimonAde looks VERY interesting but the GUI/labels just had me scratching my head. 

I think LimonADe will get a lot of love and attention by users once the interface is easier to understand :+1:
PS: what is the H/S switch?
Thanks.

**Comment by Coirt** [comment]
> Hi, I agree with Peter (I was going to raise this issue too). LimonAde looks VERY interesting but the GUI/labels just had me scratching my head.
> 
> I think LimonADe will get a lot of love and attention by users once the interface is easier to understand 
> PS: what is the H/S switch?
> Thanks.

Hard Sync/Soft Sync, I think!

**Comment by sebastien-bouffier** [comment]
Hi, yes I confirm for sync. Please let me know if v1.0.3 is better ?
Cheers

**Comment by Petervos2018** [comment]
No and yes, I can read the hover text and it works when I load an "old" vcv project with limonade in it, but....
When I insert a Limonade in a new project I can not open/import a wavetable.
It pretends to load a wav the cpu goes to 775% (on the module) but there is no wavetable loaded.
The CPU goes down (slowly) to about 1.5%.

![LimonadeBUG-103](https://user-images.githubusercontent.com/46076474/61827102-24456100-ae64-11e9-88fc-fe31b0446d4f.jpg)

BTW the hover text is GREAT !

EDIT.  I can load a wave in a frame ! just not a wavetable.

**Comment by sebastien-bouffier** [comment]
Sorry it is fixed. Available in next version.

**Comment by therealkitman** [comment]
Much easier to understand now :+1: 
However, just a little thing, the tooltip for the green Edited Frame knob only reads from 0 to 1. Should it read 1 to 256? Same issue with the red Scan knob and Range knob.
![image](https://user-images.githubusercontent.com/14888092/61843313-c188af80-aecd-11e9-9342-0cd40d934a6e.png)

**Comment by sebastien-bouffier** [comment]
Hi, yes but since frame number is variable I rescale on that segment. Frame number is available between amp and phase. v1.0.4 has been pushed. Let me know if it does make sense.

**Comment by Petervos2018** [comment]
For the few minutes I had 1.04 open in rack I was still unable to load a wavetable  in LimOnAde 
then this happened : 

I was loading an "old" project that's why there is a wavetable loaded but look at the updates : 

![Downgrade Bidoo](https://user-images.githubusercontent.com/46076474/61999989-658c7980-b0cd-11e9-8cae-98a82327542a.jpg)

Was a first for me..a downgrade, must be because of all the crashes.

**Comment by Petervos2018** [comment]
Just tried the 104fix well.... 
The last Limonade I was able to load a wavetable in, was 1.0.2. so I'm staying with that until 
you can figure out what has changed for W7 user(s) ..
Love your work,
Greetings Peter.

**Comment by sebastien-bouffier** [comment]
Hi, I am sorry that we have all those issues with that module but I keep on working to make it sable and available the sooner. We you write `Just tried the 104fix well....` do you mean that you have used my release and replaced your bidoo folder manually with my dist ?

**Comment by Petervos2018** [comment]
> replaced your bidoo folder manually with my dist ?

That is correct !

**Comment by Petervos2018** [comment]
Third of august 2019 : And now I used the version 1.0.4 from the Plugin Library and I still can't load a wavetable but I did not expect much, as it is probably the same version as the 1.0.4fix I tried earlier which also did not work.
The last working version for me is and will be 1.0.2..

Hope one day you find out what happened ;)
Thanks,
Peter.

**Comment by sebastien-bouffier** [comment]
Hi Peter,
Back from holidays => I will try to find why you can load a sample into a frame and not into a wave-table under W7.
Stay tuned

**Comment by sebastien-bouffier** [comment]
Hi Peter let me know if 1.0.5 solves the issue. Best.

**Comment by Petervos2018** [comment]
It does !
With 1.0.5 I am able to load wavetables in LiMOnade again,

Thank you very much,
Peter.
