### ISSUE TITLE
Definition of RACK_DIR is missing from Makefile

### ISSUE THREAD

**Issue by cschol** [sebastien-bouffier/Bidoo#64]
The `Makefile` should define a variable called `RACK_DIR`, which can be set to the location of the Rack source code. This allows compiling the plugin outside of the Rack source tree.

See [API Update Thread](https://github.com/VCVRack/Rack/issues/258#issuecomment-365346155).

**Comment by sebastien-bouffier** [comment]
Ok I will fix it this evening. Thanks

**Comment by sebastien-bouffier** [comment]
I just pushed the change in my make file, please tell me if it is ok.

**Comment by cschol** [comment]
Thanks for adding the definition of `RACK_DIR`. 

The only thing that is missing is to use it to find `plugin.mk`:

```
include ../../plugin.mk
```
should be

```
include $(RACK_DIR)/plugin.mk
```

**Comment by sebastien-bouffier** [comment]
I changed all ../.. by $(RACK_DIR) i.e. for arch.mk and libs tell me if i am correct.
Best.

**Comment by cschol** [comment]
Thanks! `make dep` is still failing because it is referencing `arch.mk`. Other stuff is working.

**Comment by sebastien-bouffier** [comment]
I am currently testing the make dep with 

```
RACK_DIR ?= ../../../..
include $(RACK_DIR)/arch.mk
```

seems to work, i push once test finished

**Comment by sebastien-bouffier** [comment]
done. thanks a lot for your help.

**Comment by cschol** [comment]
Perfect. Thank you! Will be added to `v2` community repo tonight.
